import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Footer from "./ui/footer";
import Header from "./ui/nav-bar/header";
import { initAction } from "./_initActions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initAction();
  return (
    <html lang="en">
      <body className={[inter.className, "flex flex-col h-screen"].join(" ")}> 
      <Header headerCSS="inset-x-0 top-0 w-full md:h-24 items-center justify-center font-mono text-sm flex flex-row gap-10" />
        {children}
      <Footer css="insert-x-0 bottom-0 left-0 flex flex-row md:h-24 w-full items-center justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black" />
      </body>
    </html>
  );
}
