import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../ui/globals.css";
import Footer from "../ui/footer";
import Navbar from "../ui/nav-bar/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
        {children}
      <Footer css="absolute insert-x-0 bottom-0 left-0 flex flex-row h-24 w-full items-center justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black" />
      </body>
    </html>
  );
}
